-- 코드를 입력하세요
# SELECT *
# FROM CAR_RENTAL_COMPANY_CAR;
# SELECT *
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY;
# SELECT *
# FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN;

# SELECT car.CAR_ID, car.CAR_TYPE, (car.DAILY_FEE * (1-discount.DISCOUNT_RATE DIV 100) * 30) as FEE
# FROM CAR_RENTAL_COMPANY_CAR car LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY history ON car.CAR_ID = history.CAR_ID 
# LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN discount ON car.CAR_TYPE = discount.CAR_TYPE
# WHERE history.START_DATE<'2022-11-01 00:00:00' 
# AND history.END_DATE<'2022-11-01 00:00:00'
# AND (car.CAR_TYPE like '세단' OR car.CAR_TYPE like 'SUV')
# AND discount.duration_type like '30일 이상'
# AND (car.DAILY_FEE * (1-discount.DISCOUNT_RATE/100) * 30)>=500000 
# AND (car.DAILY_FEE * (1-discount.DISCOUNT_RATE/100) * 30)<2000000
# GROUP BY car.car_id
# ORDER BY (car.DAILY_FEE * (1-discount.DISCOUNT_RATE/100) * 30) DESC,
# car.CAR_TYPE, car.CAR_ID;

SELECT CAR_ID, car.CAR_TYPE, TRUNCATE((30 * car.DAILY_FEE * (1-(discount.DISCOUNT_RATE/100))),0) as FEE
FROM CAR_RENTAL_COMPANY_CAR car JOIN (
    SELECT CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN discount
    WHERE DURATION_TYPE = '30일 이상') as discount
ON car.CAR_TYPE = discount.CAR_TYPE
WHERE car.CAR_TYPE IN ('세단', 'SUV')
AND car.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE>='2022-11-01' AND START_DATE<='2022-11-30'
)
AND (car.DAILY_FEE * (1-discount.DISCOUNT_RATE DIV 100) * 30) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;