-- 코드를 입력하세요
# SELECT a.ANIMAL_ID, a.NAME
# FROM ANIMAL_OUTS a LEFT JOIN ANIMAL_INS b ON a.ANIMAL_ID=b.ANIMAL_ID
# WHERE b.ANIMAL_ID IS NULL
# ORDER BY a.ANIMAL_ID, a.NAME;

SELECT o.ANIMAL_ID, o.NAME
FROM ANIMAL_OUTS o LEFT JOIN ANIMAL_INS i ON o.ANIMAL_ID=i.ANIMAL_ID
WHERE i.ANIMAL_ID IS NULL
ORDER BY o.ANIMAL_ID;