# 1. 2021년에 가입한 전체 회원들 중 상품을 구매한 회원수 (join user_id)
# 상품을 구매한 회원의 비율(=2021년에 가입한 회원 중 상품을 구매한 회원수 / 2021년에 가입한 전체 회원 수) -> 소수점 두번째자리에서 반올림
# 년, 월 별로 출력
# 년을 기준으로 오름차순 정렬 -> 월을 기준으로 오름차순 정렬

# 1.2021년에 가입한 회원 중 상품을 구매한 회원수
# SELECT YEAR(o.SALES_DATE) AS YEAR, MONTH(o.SALES_DATE) AS MONTH, COUNT(DISTINCT u.USER_ID) AS PUCHASED_USERS
# FROM ONLINE_SALE o JOIN USER_INFO u ON o.USER_ID=u.USER_ID
# WHERE u.JOINED BETWEEN '2021-01-01' AND '2021-12-31'
# GROUP BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE)

#2. 2021년에 가입한 전체 회원 수
# SELECT COUNT(DISTINCT u.USER_ID)
# FROM ONLINE_SALE o JOIN USER_INFO u ON o.USER_ID=u.USER_ID
# WHERE u.JOINED BETWEEN '2021-01-01' AND '2021-12-31'
# GROUP BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE)

# #3. 최종
SELECT YEAR(o.SALES_DATE) AS YEAR, MONTH(o.SALES_DATE) AS MONTH, COUNT(DISTINCT u.USER_ID) AS PUCHASED_USERS, ROUND(COUNT(DISTINCT u.USER_ID)/(
        SELECT COUNT(DISTINCT u.USER_ID)
        FROM USER_INFO u
        WHERE u.JOINED BETWEEN '2021-01-01' AND '2021-12-31'
    ),1) AS PUCHASED_RATIO
FROM ONLINE_SALE o JOIN USER_INFO u ON o.USER_ID=u.USER_ID
WHERE u.JOINED BETWEEN '2021-01-01' AND '2021-12-31'
GROUP BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE)
ORDER BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE)