# 생산일자(PRODUCE_DATE)가 2022년 5월인 식품들의 식품 ID, 식품 이름, 총매출을 조회
# 총매출 내림차순 -> 식품 ID 오름차순

SELECT f.PRODUCT_ID, f.PRODUCT_NAME, f.PRICE*SUM(o.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT f JOIN FOOD_ORDER o ON f.PRODUCT_ID = o.PRODUCT_ID
WHERE o.PRODUCE_DATE BETWEEN '2022.05.01' AND '2022.05.31'
GROUP BY f.PRODUCT_ID
ORDER BY f.PRICE*SUM(o.AMOUNT) DESC, PRODUCT_ID ASC;