-- 코드를 입력하세요
# SELECT B.FLAVOR
# FROM FIRST_HALF A RIGHT JOIN JULY B ON A.FLAVOR=B.FLAVOR
# GROUP BY A.FLAVOR
# ORDER BY SUM(A.TOTAL_ORDER + B.TOTAL_ORDER) DESC
# LIMIT 3;

SELECT f.FLAVOR
FROM FIRST_HALF f JOIN JULY j ON f.FLAVOR=j.FLAVOR
GROUP BY f.FLAVOR
ORDER BY SUM(f.TOTAL_ORDER+j.TOTAL_ORDER) DESC
LIMIT 3;