# DEVELOPERS 테이블에서 Front End 스킬을 가진 개발자의 정보
# ID, 이메일, 이름, 성
# ID 오름차순 정렬

#1. | 이용
SELECT DISTINCT d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
FROM DEVELOPERS d JOIN SKILLCODES s ON d.SKILL_CODE = d.SKILL_CODE|s.CODE
WHERE s.CATEGORY LIKE 'Front End'
ORDER BY d.ID;

#2. & 이용 - 1
# SELECT d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
# FROM DEVELOPERS d JOIN SKILLCODES s
# WHERE s.CODE = d.SKILL_CODE&s.CODE AND s.CATEGORY LIKE 'Front End'
# ORDER BY d.ID;

#3. & 이용 - 2
# SELECT d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
# FROM DEVELOPERS d JOIN SKILLCODES s ON s.CODE = d.SKILL_CODE&s.CODE
# WHERE s.CATEGORY LIKE 'Front End'
# ORDER BY d.ID;