-- 코드를 입력하세요
SELECT i.ANIMAL_ID, i.NAME
FROM ANIMAL_INS i JOIN ANIMAL_OUTS o ON i.ANIMAL_ID = o.ANIMAL_ID
WHERE i.DATETIME>o.DATETIME
ORDER BY i.DATETIME;

# SELECT A.ANIMAL_ID, A.NAME
# FROM ANIMAL_INS A JOIN ANIMAL_OUTS B ON A.ANIMAL_ID=B.ANIMAL_ID
# WHERE A.DATETIME>B.DATETIME
# ORDER BY A.DATETIME;