-- 2021년에 출판
-- '인문' 카테고리
-- BOOK_ID, PUBLISHED_DATE 출력
-- 출판일을 기준으로 오름차순

SELECT BOOK_ID, TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD')
FROM BOOK
WHERE EXTRACT(YEAR FROM PUBLISHED_DATE) = 2021
AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE;